#pragma config(Sensor, dgtl1,  enc1,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  enc2,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  enc3,           sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  enc4,           sensorQuadEncoder)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motor4,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const short leftButton = 1;
//const short centerButton = 2;
//const short rightButton = 4;
const float minVolt=7.75;
const int testMsecs=1500;
const int REPS=5; // # of reptitions
task main()
{
	float voltage=nImmediateBatteryLevel/1000.0;
	string mainBattery;
	bLCDBacklight = true;                 // Turn on LCD Backlight
	clearLCDLine(0);                      // Clear line 1 (0) of the LCD
	clearLCDLine(1);                      // Clear line 2 (1) of the LCD
	displayLCDPos(0,0);
	displayNextLCDString("Left Btn Start");
	displayLCDString(1, 0, "Voltage: ");
	sprintf(mainBattery, "%1.2f%c",voltage,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	while(true){

		if(nLCDButtons==leftButton){
			if(voltage>= minVolt){
				int enc1Tot=0;
				int enc2Tot=0;
				int enc3Tot=0;
				int enc4Tot=0;
				for(int i=0; i<REPS; i+=1)
				{
					SensorValue(enc1)=0;
					SensorValue(enc2)=0;
					SensorValue(enc3)=0;
					SensorValue(enc4)=0;
					startMotor(motor1,127);
					startMotor(motor2,127);
					startMotor(motor3,127);
					startMotor(motor4,127);
					wait1Msec (testMsecs);
					int enc1v=abs(SensorValue(enc1));
					enc1Tot+=enc1v;
					int enc2v=abs(SensorValue(enc2));
					enc2Tot+=(enc2v-3);
					int enc3v=abs(SensorValue(enc3));
					enc3Tot+=(enc3v-73);
					int enc4v=abs(SensorValue(enc4));
					enc4Tot+=(enc4v-84);
					stopMotor (motor1);
					stopMotor (motor2);
					stopMotor (motor3);
					stopMotor (motor4);
					while(enc1v-abs(SensorValue(enc1))<0)
					{
						enc1v=abs(SensorValue(enc1));
						wait1Msec (5);
					}
					wait1Msec (1000);
				}
				clearLCDLine(0);                      // Clear line 1 (0) of the LCD
				clearLCDLine(1);                      // Clear line 2 (1) of the LCD
				bLCDBacklight = true;                 // Turn on LCD Backlight
				displayLCDPos(0,0);
				displayNextLCDString("E1:");
				displayNextLCDNumber(enc1Tot/REPS);
				displayLCDPos(0,8);
				displayNextLCDString("E2:");
				displayNextLCDNumber(enc2Tot/REPS);
				displayLCDPos(1,0);
				displayNextLCDString("E3:");
				displayNextLCDNumber(enc3Tot/REPS);
				displayLCDPos(1,8);
				displayNextLCDString("E4:");
				displayNextLCDNumber(enc4Tot/REPS);
			}
			else
			{
				clearLCDLine(0);                      // Clear line 1 (0) of the LCD
				clearLCDLine(1);                      // Clear line 2 (1) of the LCD
				displayLCDPos(0,0);
				displayNextLCDString("Voltage Low");
				displayLCDString(1, 0, "Voltage: ");
				sprintf(mainBattery, "<%1.2f%c",minVolt,'V'); //Build the value to be displayed
				displayNextLCDString(mainBattery);

			}
		}
	}
}
